#! /usr/bin/env python
import requests
import os
import json
import MySQLdb as mysql
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def get_key():
    with open("info.json") as data:
        json_data = json.load(data)
    return json_data



def get_thread_comments():
    disqus_data = get_key()
    secret_api_key = disqus_data["disqus"][0]["secret_api_key"]
    forum_name = disqus_data["disqus"][0]["forum_name"]
    forum_data = requests.get("http://disqus.com/api/3.0/forums/listPosts.json?api_key=%s&forum=%s" % (secret_api_key, forum_name)).json()
    i = 0
    threadlist = []
    while i < len(forum_data["response"]):
        thread_raw_message = str(forum_data["response"][i]["raw_message"])
        thread_id  = str(forum_data["response"][i]["thread"])
        thread_data = requests.get("http://disqus.com/api/3.0/threads/list.json?api_key=%s&forum=%s&thread=%s" %(secret_api_key, forum_name, thread_id)).json()
        thread_url = str(thread_data["response"][0]["link"])
        book_name, chapter_name =  thread_url.split("/")[-2:]
        query_url = book_name+"/"+ chapter_name
        thread_comments = {}
        thread_comments["Comments"] = thread_raw_message
        thread_comments["QueryUrl"]= query_url
        thread_comments["ThreadUrl"]= thread_url
        threadlist.append(thread_comments)

        i += 1

    return threadlist

  

def connect_db():
    database_auth = get_key()
    details = get_thread_comments()
    com = mysql.connect(user = "root", db = database_auth["database"][0]["db"], passwd = database_auth["database"][0]["password"])
    con = com.cursor()
    urllist = [str(details[i]["QueryUrl"]) for i in range(len(details))]
    print urllist
    contributor_list = []
    for notebook in urllist:
        contributor_dict = {} 
        con.execute("""select email, first_name, last_name from auth_user where id = (SELECT contributor_id FROM `tbc_book` where id = (select book_id from tbc_chapters where notebook= '%s'))""" % notebook)
    
        contributor_details = con.fetchall()
        contributor_dict["email"] = contributor_details[0][0]
        contributor_dict["first_name"] = contributor_details[0][1]
        contributor_dict["last_name"] = contributor_details[0][2]
        contributor_list.append(contributor_dict)
    print contributor_list


def send_email():
    connect = smtplib.SMTP("smtp.fossee.in", "enter port here")
    connect.ehlo()
    connect.starttls()
    connect.login("locahost")
    to = "get it from contributor_list"
    subject = "You have New Comments"
    message = "This is an autogenerated message. You have new comments. Please check."

    msg = MIMEMultipart()
    msg['from'] = username
    msg['to'] = toemail
    msg['subject'] = thesubject
    msg.attach(MIMEText(yourmessage))
    connect.sendmail(username, toemail, msg.as_string())
    connect.close()



   

if __name__ == "__main__":

    a =  connect_db()
    print a
